Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

 # proxy
  config.vm.define "proxy" do |proxy|
  proxy.vm.box = "hashicorp/bionic64"
  proxy.vm.hostname = "proxy"
  proxy.vm.network "private_network", ip: "192.168.70.10"

  proxy.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh" # Проброс порта SSH
  proxy.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx" # Проброс порта Nginx

  # SSH-настройки
  proxy.vm.provider "virtualbox" do |v|
  v.name = "reverse-proxy" # Имя виртуальной машины
  end
  # Настройка провиженинга (установка пакетов и настройка Nginx)
  proxy.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y nginx

  # Настройка Nginx в качестве обратного прокси
  echo 'server {
  listen 80;
  location / {
    proxy_pass http://192.168.33.11/;
  }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null
  
  sudo service nginx restart
SHELL
 end


# front
config.vm.define "front" do |front|
front.vm.box = "hashicorp/bionic64"
front.vm.network "private_network", ip: "192.168.70.11"
front.vm.provider "virtualbox" do |v|
  v.name = "front" # Имя виртуальной машины
  end

front.vm.provision "shell", inline: <<-SHELL
  # Обновление пакетов
  sudo apt-get update
  sudo apt-get install -y git
    git config --global user.name "szanko02"
    git config --global user.email "stas.060232@gmail.com"
    sudo git clone https://github.com/szanko02/devops-training-project-frontend /front
  # Установка Nginx
  sudo apt-get install -y nginx

  # Установка Node.js
  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  sudo apt-get install -y nodejs
  SHELL
end



 #back
 config.vm.define "back" do |back|
  back.vm.box = "hashicorp/bionic64"
  back.vm.hostname = "back"
  back.vm.network "private_network", ip: "192.168.70.12"

  back.vm.provider "virtualbox" do |v|
  v.name = "back" # Имя виртуальной машины
  end

  back.vm.provision "shell", inline: <<-SHELL
    echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc
    echo "export JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre" >> ~/.bashrc
    source ~/.bashrc
    sudo apt-get update
    sudo apt-get install -y git
    git config --global user.name "szanko02"
    git config --global user.email "stas.060232@gmail.com"
    sudo git clone https://github.com/szanko02/devops-training-project-backend /back
    sudo apt-get install -y openjdk-8-jdk
  SHELL
   end


 #db
  config.vm.define "db" do |db|
  db.vm.box = "hashicorp/bionic64"
  db.vm.hostname = "db"
  db.vm.network "private_network", ip: "192.168.70.13"
  db.vm.provider "virtualbox" do |v|
    v.name = "db" # Имя виртуальной машины
    end
  db.vm.provision "shell", inline: <<-SHELL
  # Обновление пакетов
  sudo apt-get update

  # Установка MySQL
  sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
  sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
  sudo apt-get install -y mysql-server
  SHELL
 end
end